export const TECH_ICONS: Record<string, string> = {
  "next.js": "/nextjs.svg",
  nextjs: "/nextjs.svg",
  react: "/react.svg",
  tailwindcss: "/tailwind.svg",
  supabase: "/supabase.png",
  rust: "/rust.png",
  node: "/nodejs.png",
  postgresql: "/postgresql.png",
  docker: "/docker.png",
  github: "/github.png",
  vps: "/vps.png",
  coolify: "/coolify.png",
  vercel: "/vercel.svg",
  clerk: "/clerk.svg",
  "better auth": "/betterauth.svg",
  shadcn: "/shadcn.svg",
  tokio: "/tokio.svg",
  ffmpeg: "/ffmpeg.svg",
  "framer motion": "/framermotion.svg",
};
